name: Update Gist

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 6 * * *"
      
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Update gist
        run: npm run status
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: d053847bdfb018d8e22f1ddd7caddfc4
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
